### PR TITLE
Chat session id is stored in localStorage and is sent to daemon in in…

### LINKED ISSUE #31: Recall chat history when previously connected
Placeholder

### PR DESCRIPTION
**Pull request by broneks**
…itial socket handshake.

**What**:

**Why**:
this will allow the same chat session to persists across browser refresh.

**How**:

close #31

### CODE REVIEW

**Comment by broneks** [comment]
@mihok so I was wondering... is it a security concern to store the chat id in localStorage? Can someone tamper it and end up recreating someone else's chat id and steal their session? I'm not sure, but if that's the case then I think we could maybe use a combination of chat id AND creation timestamp.

**Comment by mihok** [comment]
Hmmm, good question.

I'm not sure, the chat ID is generated by socketio and is a (I think) random string, so my thinking is that it is already difficult to reproduce without brute forcing or having access to the memory on the daemon. I'm not certain, but I think we can leave it just as the chat ID for now

**Comment by mihok** [comment]
Also, your eslint is failing in travis

**Comment by broneks** [comment]
half of this eslint isn't from my PR. But I'll fix it!

**Comment by broneks** [comment]
screen shot 2017-09-01 at 09 07 30

it's strange that I don't get these errors locally. Hmm I'll investigate.

**Comment by broneks** [comment]
this is a pain in the ass. Can someone checkout the branch and see if they get any errors?

**Comment by mihok** [comment]
I'll check it out and see whats what

**Comment by mihok** [comment]
I cant replicate the errors either, but I have a burning desire to understand why Travis thinks they are different :E

**Comment by mihok** [comment]
I was able to reproduce this on my local after a fresh yarn install. It looks a later version of eslint or prettier or something does not like class property initializers ... Still trying to figure out how to resolve this problem

**Comment by mihok** [comment]
Cool, looked like it was an issue with prettier-eslint _I believe_, after upgrading some packages, it now builds as expected. I would `rm -r node_modules` and then `yarn install` again,

**Pull request merged**
